name: Check Version
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
    - name: Check version
      run: |
        # Get version from GRUB
        GRUB_V=$(git ls-remote --tags https://git.savannah.gnu.org/git/grub.git | awk -F/ '{print $3}' | grep -Ev 'rc|beta|\^' | grep 'grub-' | sort -V | tail -1)
        
        # Get version from this repo
        AVAILABLE_V=$(curl -s \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.tag_name')
        
        # Check if versions are empty or null
        if [ -z "$GRUB_V" ] || [ "$GRUB_V" = "null" ] || [ -z "$AVAILABLE_V" ] || [ "$AVAILABLE_V" = "null" ]; then
          echo "Couldn't get Version numbers"
          exit 1
        fi

        if [ "${GRUB_V#*-}" != "${AVAILABLE_V#v}" ]; then
          echo "Newer version found: v${GRUB_V#*-}"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/snapraid.yml/dispatches" \
            -d "{\"ref\":\"master\"}"
        else
          echo "Nothing to do"
        fi
